{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "44ef34c7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "REQUIRED_COLUMNS = {\"order_date\", \"carrier\", \"delivery_time_days\"}\n",
    "\n",
    "\n",
    "def load_and_validate_csv(path: str) -> pd.DataFrame:\n",
    "    # 1) Základní kontrola existence souboru\n",
    "    if not os.path.exists(path):\n",
    "        raise FileNotFoundError(f\"Soubor '{path}' nebyl nalezen.\")\n",
    "\n",
    "    # 2) Načtení CSV (s jednoduchým ošetřením chyby čtení)\n",
    "    try:\n",
    "        df = pd.read_csv(path)\n",
    "    except Exception as exc:\n",
    "        raise RuntimeError(f\"Nepodařilo se načíst CSV '{path}': {exc}\") from exc\n",
    "\n",
    "    # 3) Kontrola povinných sloupců\n",
    "    missing = REQUIRED_COLUMNS - set(df.columns)\n",
    "    if missing:\n",
    "        raise ValueError(\n",
    "            f\"V CSV chybí povinné sloupce: {sorted(missing)}. \"\n",
    "            f\"Nalezené sloupce: {list(df.columns)}\"\n",
    "        )\n",
    "\n",
    "    # 4) Převod order_date na datetime + normalizace na den\n",
    "    df[\"order_date\"] = pd.to_datetime(df[\"order_date\"], errors=\"coerce\").dt.normalize()\n",
    "    if df[\"order_date\"].isna().any():\n",
    "        bad = df[df[\"order_date\"].isna()].head(5)\n",
    "        raise ValueError(\n",
    "            \"Některé hodnoty 'order_date' nelze převést na datum. Ukázka (max 5):\\n\"\n",
    "            f\"{bad}\"\n",
    "        )\n",
    "\n",
    "    # 5) Převod delivery_time_days na číslo\n",
    "    df[\"delivery_time_days\"] = pd.to_numeric(df[\"delivery_time_days\"], errors=\"coerce\")\n",
    "    if df[\"delivery_time_days\"].isna().any():\n",
    "        bad = df[df[\"delivery_time_days\"].isna()].head(5)\n",
    "        raise ValueError(\n",
    "            \"Některé hodnoty 'delivery_time_days' nelze převést na číslo. Ukázka (max 5):\\n\"\n",
    "            f\"{bad}\"\n",
    "        )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "def compute_daily_and_baseline(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    # 6) Denní agregace: průměr delivery_time_days za (order_date, carrier)\n",
    "    daily = (\n",
    "        df.groupby([\"order_date\", \"carrier\"], as_index=False)[\"delivery_time_days\"]\n",
    "        .mean()\n",
    "        .rename(columns={\"delivery_time_days\": \"daily_avg_delivery\"})\n",
    "        .sort_values([\"carrier\", \"order_date\"])\n",
    "        .reset_index(drop=True)\n",
    "    )\n",
    "\n",
    "    # 7) Pro každého dopravce doplnit chybějící dny + spočítat baseline\n",
    "    parts = []\n",
    "    for carrier_value, g in daily.groupby(\"carrier\", sort=False):\n",
    "        # 7a) Necháme jen to, co potřebujeme, a order_date dáme do indexu\n",
    "        g = g.sort_values(\"order_date\").set_index(\"order_date\")[[\"daily_avg_delivery\"]]\n",
    "\n",
    "        # 7b) Kompletní denní osa pro dopravce (min..max)\n",
    "        full_dates = pd.date_range(g.index.min(), g.index.max(), freq=\"D\")\n",
    "\n",
    "        # 7c) Reindex => doplnění chybějících dní (NaN v daily_avg_delivery)\n",
    "        g = g.reindex(full_dates)\n",
    "        g.index.name = \"order_date\"\n",
    "\n",
    "        # 7d) Doplnit carrier konstantou\n",
    "        g[\"carrier\"] = carrier_value\n",
    "\n",
    "        # 7e) Baseline: předchozích 14 kalendářních dní bez aktuálního dne, min_periods=7\n",
    "        g[\"baseline_14d\"] = (\n",
    "            g[\"daily_avg_delivery\"]\n",
    "            .shift(1)\n",
    "            .rolling(window=14, min_periods=7)\n",
    "            .mean()\n",
    "        )\n",
    "\n",
    "        parts.append(g.reset_index())\n",
    "\n",
    "    daily_full = pd.concat(parts, ignore_index=True)\n",
    "\n",
    "    # 8) pct_change + anomálie\n",
    "    # Vypočítat pct_change a příznak anomálie podle pravidla > 30 % nad baseline\n",
    "    daily_full[\"pct_change\"] = (daily_full[\"daily_avg_delivery\"] / daily_full[\"baseline_14d\"]) - 1\n",
    "    # Anomálie počítáme jen tam, kde existuje aktuální hodnota i baseline\n",
    "    daily_full[\"is_anomaly\"] = (\n",
    "        daily_full[\"daily_avg_delivery\"].notna()\n",
    "        & daily_full[\"baseline_14d\"].notna()\n",
    "        & (daily_full[\"daily_avg_delivery\"] > 1.30 * daily_full[\"baseline_14d\"])\n",
    "    )\n",
    "\n",
    "    # 9) Výstup ve formátu dle zadání\n",
    "    return daily_full[\n",
    "        [\"order_date\", \"carrier\", \"daily_avg_delivery\", \"baseline_14d\", \"pct_change\", \"is_anomaly\"]\n",
    "    ].sort_values([\"order_date\", \"carrier\"]).reset_index(drop=True)\n",
    "\n",
    "\n",
    "def main(input_path: str, output_path: str) -> None:\n",
    "    # 10) Načíst a zvalidovat data\n",
    "    df = load_and_validate_csv(input_path)\n",
    "\n",
    "    # 11) Spočítat denní průměry + baseline + anomálie\n",
    "    result = compute_daily_and_baseline(df)\n",
    "\n",
    "    # 12) Vyfiltrovat anomálie a vypsat je\n",
    "    anomalies = result[result[\"is_anomaly\"]].copy()\n",
    "\n",
    "    if anomalies.empty:\n",
    "        print(\"Žádné anomálie nebyly nalezeny (daily_avg_delivery > 1.30 * baseline_14d).\")\n",
    "    else:\n",
    "        print(anomalies.to_string(index=False))\n",
    "\n",
    "    # 13) Uložit anomálie do CSV\n",
    "    anomalies.to_csv(output_path, index=False)\n",
    "    print(f\"\\nUloženo: {output_path}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    try:\n",
    "        main(\n",
    "            r\"C:\\Users\\Pavla\\Downloads\\alensa_dummy_dataset.csv\",\n",
    "            r\"C:\\Users\\Pavla\\Downloads\\anomalies_delivery_time.csv\",\n",
    "        )\n",
    "    except Exception as exc:\n",
    "        print(f\"Chyba: {exc}\", file=sys.stderr)\n",
    "        sys.exit(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "615275c2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
